version: "3.8"

services:
  muttley:
    image: mtimani/muttley
    container_name: muttley
    restart: always
    ports:
      - "80:5000"
    # Not required => Use only if BasicAuth needed
    environment:
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=supersecurepassword
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=production
    entrypoint: ["/bin/bash", "/server/run.sh"]
